recipes = [ { publisher: 'The Pioneer Woman',
    f2f_url: 'http://food2fork.com/view/47023',
    title: 'Spicy Pasta Salad with Smoked Gouda, Tomatoes, and Basil',
    source_url: 'http://thepioneerwoman.com/cooking/2011/06/spicy-pasta-salad-with-smoked-gouda-tomatoes-and-basil/',
    recipe_id: '47023',
    image_url: 'http://static.food2fork.com/5842229930_73a968f08e_zab23.jpg',
    social_rank: 99.99999999999517,
    publisher_url: 'http://thepioneerwoman.com' },
  { publisher: 'Simply Recipes',
    f2f_url: 'http://food2fork.com/view/36808',
    title: 'Quinoa Salad with Black Beans, Corn, and Tomatoes',
    source_url: 'http://www.simplyrecipes.com/recipes/quinoa_salad_with_black_beans_corn_and_tomatoes/',
    recipe_id: '36808',
    image_url: 'http://static.food2fork.com/quinoablackbeansalada1300x20052f36ae2.jpg',
    social_rank: 99.99999999458153,
    publisher_url: 'http://simplyrecipes.com' },
  { publisher: 'The Pioneer Woman',
    f2f_url: 'http://food2fork.com/view/47041',
    title: 'Pasta Salad with Tomatoes, Zucchini, and Feta',
    source_url: 'http://thepioneerwoman.com/cooking/2011/03/pasta-salad-with-tomatoes-zucchini-and-feta/',
    recipe_id: '47041',
    image_url: 'http://static.food2fork.com/5566512470_9e98939ab3_z2766.jpg',
    social_rank: 99.99999855322939,
    publisher_url: 'http://thepioneerwoman.com' },
  { publisher: 'Epicurious',
    f2f_url: 'http://food2fork.com/view/9a88d4',
    title: 'Tomato Salad with Shallot Vinaigrette, Capers, and Basil',
    source_url: 'http://www.epicurious.com/recipes/food/views/Tomato-Salad-with-Shallot-Vinaigrette-Capers-and-Basil-395510',
    recipe_id: '9a88d4',
    image_url: 'http://static.food2fork.com/395510f3b6.jpg',
    social_rank: 99.99989415559496,
    publisher_url: 'http://www.epicurious.com' },
  { publisher: '101 Cookbooks',
    f2f_url: 'http://food2fork.com/view/47859',
    title: 'Heirloom Tomato Salad',
    source_url: 'http://www.101cookbooks.com/archives/heirloom-tomato-salad-recipe.html',
    recipe_id: '47859',
    image_url: 'http://static.food2fork.com/tomato_salad_recipedc47.jpg',
    social_rank: 99.99956954982561,
    publisher_url: 'http://www.101cookbooks.com' },
  { publisher: 'Two Peas and Their Pod',
    f2f_url: 'http://food2fork.com/view/54483',
    title: 'Black Quinoa Salad with Mango, Avocado, & Tomatoes',
    source_url: 'http://www.twopeasandtheirpod.com/black-quinoa-salad-with-mango-avocado-tomatoes/',
    recipe_id: '54483',
    image_url: 'http://static.food2fork.com/blackquinoasalad4632f.jpg',
    social_rank: 99.99868467735365,
    publisher_url: 'http://www.twopeasandtheirpod.com' },
  { publisher: 'BBC Good Food',
    f2f_url: 'http://food2fork.com/view/3e0262',
    title: 'Salmon &amp; broccoli cakes with watercress, avocado &amp; tomato salad',
    source_url: 'http://www.bbcgoodfood.com/recipes/1898643/salmon-and-broccoli-cakes-with-watercress-avocado-',
    recipe_id: '3e0262',
    image_url: 'http://static.food2fork.com/1898643_MEDIUMd188.jpg',
    social_rank: 99.9980605197234,
    publisher_url: 'http://www.bbcgoodfood.com' },
  { publisher: 'Epicurious',
    f2f_url: 'http://food2fork.com/view/cb6928',
    title: 'Charred Corn Salad with Basil and Tomatoes',
    source_url: 'http://www.epicurious.com/recipes/food/views/Charred-Corn-Salad-with-Basil-and-Tomatoes-51104300',
    recipe_id: 'cb6928',
    image_url: 'http://static.food2fork.com/511043003a29.jpg',
    social_rank: 99.99336784564272,
    publisher_url: 'http://www.epicurious.com' },
  { publisher: 'Epicurious',
    f2f_url: 'http://food2fork.com/view/dac642',
    title: 'Tomato and Watermelon Salad',
    source_url: 'http://www.epicurious.com/recipes/food/views/Tomato-and-Watermelon-Salad-352389',
    recipe_id: 'dac642',
    image_url: 'http://static.food2fork.com/352389b99f.jpg',
    social_rank: 99.98813555265303,
    publisher_url: 'http://www.epicurious.com' },
  { publisher: 'The Pioneer Woman',
    f2f_url: 'http://food2fork.com/view/7da689',
    title: 'Quick-Marinated Cherry Tomato Salad',
    source_url: 'http://thepioneerwoman.com/cooking/2013/03/recipes-from-tomorrows-show-2/',
    recipe_id: '7da689',
    image_url: 'http://static.food2fork.com/beattheclock1f28.jpg',
    social_rank: 99.97840078112634,
    publisher_url: 'http://thepioneerwoman.com' },
  { publisher: 'BBC Good Food',
    f2f_url: 'http://food2fork.com/view/0a6996',
    title: 'Warm Puy lentil, cherry tomato &amp; halloumi salad',
    source_url: 'http://www.bbcgoodfood.com/recipes/6177/warm-puy-lentil-cherry-tomato-and-halloumi-salad',
    recipe_id: '0a6996',
    image_url: 'http://static.food2fork.com/6177_MEDIUMadd8.jpg',
    social_rank: 99.96856985988858,
    publisher_url: 'http://www.bbcgoodfood.com' },
  { publisher: 'Epicurious',
    f2f_url: 'http://food2fork.com/view/20d4ea',
    title: 'Cucumber, Tomato and Feta Salad',
    source_url: 'http://www.epicurious.com/recipes/food/views/Cucumber-Tomato-and-Feta-Salad-365671',
    recipe_id: '20d4ea',
    image_url: 'http://static.food2fork.com/3656714f4f.jpg',
    social_rank: 99.9640876699839,
    publisher_url: 'http://www.epicurious.com' },
  { publisher: 'Simply Recipes',
    f2f_url: 'http://food2fork.com/view/37085',
    title: 'Tomato, Onion, Avocado Salad',
    source_url: 'http://www.simplyrecipes.com/recipes/tomato_onion_avocado_salad/',
    recipe_id: '37085',
    image_url: 'http://static.food2fork.com/tomatoonionavocadosalad300x200d05bd536.jpg',
    social_rank: 99.95033362196136,
    publisher_url: 'http://simplyrecipes.com' },
  { publisher: 'Real Simple',
    f2f_url: 'http://food2fork.com/view/39770',
    title: 'Tomato, Cucumber, and Quinoa Salad',
    source_url: 'http://www.realsimple.com/food-recipes/browse-all-recipes/tomato-cucumber-quinoa-salad-00100000083528/index.html',
    recipe_id: '39770',
    image_url: 'http://static.food2fork.com/quinoatomatocucumberictcrop_3007e3642a4.jpg',
    social_rank: 99.9487709625423,
    publisher_url: 'http://realsimple.com' },
  { publisher: 'The Pioneer Woman',
    f2f_url: 'http://food2fork.com/view/47220',
    title: 'Sundried Tomato Pasta Salad',
    source_url: 'http://thepioneerwoman.com/cooking/2009/06/fourth-of-july-week-sundried-tomato-pasta-salad/',
    recipe_id: '47220',
    image_url: 'http://static.food2fork.com/3673433059_6b22c2887147bf.jpg',
    social_rank: 99.84705172461854,
    publisher_url: 'http://thepioneerwoman.com' },
  { publisher: 'Cookin Canuck',
    f2f_url: 'http://food2fork.com/view/6a7998',
    title: 'Whole Wheat Pasta Salad with Salmon, Tomatoes & Herb Dressing',
    source_url: 'http://www.cookincanuck.com/2012/04/whole-wheat-pasta-salad-recipe-with-salmon-tomatoes-herb-dressing-for-a-half-marathon/',
    recipe_id: '6a7998',
    image_url: 'http://static.food2fork.com/6938946520_1a106c7a202300x300015a.jpg',
    social_rank: 99.79044584205086,
    publisher_url: 'http://www.cookincanuck.com' },
  { publisher: 'Epicurious',
    f2f_url: 'http://food2fork.com/view/eabd9b',
    title: 'Grilled Steak Salad with Tomato Vinaigrette',
    source_url: 'http://www.epicurious.com/recipes/food/views/Grilled-Steak-Salad-with-Tomato-Vinaigrette-51104280',
    recipe_id: 'eabd9b',
    image_url: 'http://static.food2fork.com/51104280e8bc.jpg',
    social_rank: 99.38356801416714,
    publisher_url: 'http://www.epicurious.com' },
  { publisher: 'Cookin Canuck',
    f2f_url: 'http://food2fork.com/view/8887d5',
    title: 'Farro Salad Recipe with Sun-Dried Tomatoes, Spinach & Cashews',
    source_url: 'http://www.cookincanuck.com/2013/02/farro-salad-recipe-sun-dried-tomato-spinach-cashews/',
    recipe_id: '8887d5',
    image_url: 'http://static.food2fork.com/IMG_53185293.jpg',
    social_rank: 99.21412722992767,
    publisher_url: 'http://www.cookincanuck.com' },
  { publisher: 'Bon Appetit',
    f2f_url: 'http://food2fork.com/view/49143',
    title: 'Charred Corn Salad with Basil and Tomatoes',
    source_url: 'http://www.bonappetit.com/recipes/2012/07/charred-corn-salad-with-basil-and-tomatoes',
    recipe_id: '49143',
    image_url: 'http://static.food2fork.com/charredcornsaladwithbasilandtomatoes646e117.jpg',
    social_rank: 98.38250817488569,
    publisher_url: 'http://www.bonappetit.com' },
  { publisher: 'Cookin Canuck',
    f2f_url: 'http://food2fork.com/view/cca960',
    title: 'Greek Grilled Lamb Chops Recipe with Tomato, Cucumber & Kalamata Olive Salad',
    source_url: 'http://www.cookincanuck.com/2012/06/greek-grilled-lamb-chops-recipe-with-tomato-cucumber-kalamata-olive-salad/',
    recipe_id: 'cca960',
    image_url: 'http://static.food2fork.com/GreekGrilledLambSquarebc62.jpg',
    social_rank: 97.66060725584089,
    publisher_url: 'http://www.cookincanuck.com' },
  { publisher: 'Real Simple',
    f2f_url: 'http://food2fork.com/view/38427',
    title: 'Chicken Kebabs With Tomato Salad',
    source_url: 'http://www.realsimple.com/food-recipes/browse-all-recipes/chicken-kebabs-grilled-corn-tomato-salad-00000000015765/index.html',
    recipe_id: '38427',
    image_url: 'http://static.food2fork.com/20minkebabcorn_30038e2b10e.jpg',
    social_rank: 97.41628558856691,
    publisher_url: 'http://realsimple.com' },
  { publisher: 'Simply Recipes',
    f2f_url: 'http://food2fork.com/view/35926',
    title: 'Cherry Tomato Orzo Salad',
    source_url: 'http://www.simplyrecipes.com/recipes/cherry_tomato_orzo_salad/',
    recipe_id: '35926',
    image_url: 'http://static.food2fork.com/cherrytomatoorzofetasalad300x200082e127f.jpg',
    social_rank: 97.26536479544889,
    publisher_url: 'http://simplyrecipes.com' },
  { publisher: 'Chow',
    f2f_url: 'http://food2fork.com/view/b0cbde',
    title: 'Tomato, Tomatillo, and Corn Salad with Avocado Dressing Recipe',
    source_url: 'http://www.chow.com/recipes/30355-tomato-tomatillo-and-corn-salad-with-avocado-dressing',
    recipe_id: 'b0cbde',
    image_url: 'http://static.food2fork.com/30355_RecipeImage_620x413_tomato_tomatillo_salad_avocado_dressing64bf.jpg',
    social_rank: 96.71760678607573,
    publisher_url: 'http://www.chow.com' },
  { publisher: 'BBC Food',
    f2f_url: 'http://food2fork.com/view/64c246',
    title: 'Panzanella (Tuscan tomato and bread salad)',
    source_url: 'http://www.bbc.co.uk/food/recipes/panzanella_tuscan_tomato_09380',
    recipe_id: '64c246',
    image_url: 'http://static.food2fork.com/panzanella_tuscan_tomato_09380_16x9dc0f.jpg',
    social_rank: 96.71515972465346,
    publisher_url: 'http://www.bbc.co.uk/food' },
  { publisher: 'Bon Appetit',
    f2f_url: 'http://food2fork.com/view/50075',
    title: 'Cucumber, Tomato, and Feta Salad',
    source_url: 'http://www.bonappetit.com/recipes/2011/06/cucumber-tomato-and-feta-salad',
    recipe_id: '50075',
    image_url: 'http://static.food2fork.com/marecucumbertomatoandfetasaladh0d16.jpg',
    social_rank: 96.43720445651755,
    publisher_url: 'http://www.bonappetit.com' },
  { publisher: 'Cookie and Kate',
    f2f_url: 'http://food2fork.com/view/e670de',
    title: 'All Recipes',
    source_url: 'http://cookieandkate.com/2012/stacked-tomato-summer-vegetable-and-grilled-bread-salad/',
    recipe_id: 'e670de',
    image_url: 'http://static.food2fork.com/stackedsummertomatozucchinisaladrecipe19128.jpg',
    social_rank: 89.79857396798705,
    publisher_url: 'http://cookieandkate.com' },
  { publisher: 'Bon Appetit',
    f2f_url: 'http://food2fork.com/view/49711',
    title: 'Flank Steak with Bloody Mary Tomato Salad',
    source_url: 'http://www.bonappetit.com/recipes/2011/07/flank-steak-with-bloody-mary-tomato-salad',
    recipe_id: '49711',
    image_url: 'http://static.food2fork.com/flanksteakwithbloodymarytomatosaladhe056.jpg',
    social_rank: 96.08963569553556,
    publisher_url: 'http://www.bonappetit.com' },
  { publisher: 'Jamie Oliver',
    f2f_url: 'http://food2fork.com/view/8f79f8',
    title: 'Ricotta fritters with tomato sauce &amp; courgette salad',
    source_url: 'http://www.jamieoliver.com/recipes/cheese-recipes/ricotta-fritters-with-tomato-sauce-courgette-salad',
    recipe_id: '8f79f8',
    image_url: 'http://static.food2fork.com/859_1_1354901447_lrgbc51.jpg',
    social_rank: 95.99120029478243,
    publisher_url: 'http://www.jamieoliver.com' },
  { publisher: 'Real Simple',
    f2f_url: 'http://food2fork.com/view/37546',
    title: 'Stuffed Chicken Breasts With Tomato Salad',
    source_url: 'http://www.realsimple.com/food-recipes/browse-all-recipes/stuffed-chicken-breasts-tomato-salad-10000001736028/index.html',
    recipe_id: '37546',
    image_url: 'http://static.food2fork.com/stuffedchickentomato_3009dddd450.jpg',
    social_rank: 95.73920898891305,
    publisher_url: 'http://realsimple.com' },
  { publisher: 'Real Simple',
    f2f_url: 'http://food2fork.com/view/39202',
    title: 'Havarti-Stuffed Chicken With Tomato Salad',
    source_url: 'http://www.realsimple.com/food-recipes/browse-all-recipes/havarti-stuffed-chicken-00000000037520/index.html',
    recipe_id: '39202',
    image_url: 'http://static.food2fork.com/chickentomato_300461eba53.jpg',
    social_rank: 95.58290628333617,
    publisher_url: 'http://realsimple.com' } ]


let preferredPublishers = ["Bon Appetit", "Serious Eats", "Smitten Kitchen", "Simply Recipes"];


transformedRecipes = recipes.sort(function(recipeA, recipeB) {
  return scoreRecipe(recipeA) - scoreRecipe(recipeB);
});

function scoreRecipe(recipe) {
  let indexOfRecipe = preferredPublishers.indexOf(recipe.publisher);
  if (indexOfRecipe == -1) {
    return 100;
  } else {
    return indexOfRecipe;
  }
}

console.log(transformedRecipes);
